//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LazyLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;Word of Recall (OLD)
        ///3;Word of Mass Recall (OLD)
        ///4;Word of Recall Other
        ///5;Death Touch
        ///7;Suicide
        ///10;Blizzard
        ///13;Swim Speed (TEST)
        ///14;Mana Drain
        ///17;Power Word: Shield
        ///22;Super Food (TEST)
        ///24;Major Heal Self (TEST)
        ///25;Stun
        ///26;Bind Self (TEST)
        ///27;Goldshire Portal
        ///31;Teleport Goldshire
        ///33;Teleport Westfall
        ///34;Teleport Duskwood
        ///35;Teleport Elwynn
        ///45;War Stomp
        ///53;Backstab
        ///56;Stun
        ///59;Normal bow shot (TEST)
        ///65;Haste
        ///66;Invisibility
        ///71;Defensive Stance
        ///75;Auto Shot
        ///77;Turtle&apos;s Shell
        ///78;He [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
    }
}
